/// The sounds the app plays (#95): each a bundled 44.1 kHz mono 16-bit WAV
/// generated by `tools/sfx.py`, recorded in `assets/audio/LICENSES.md`.
/// `test/guards/audio_assets_test.dart` derives "the clips the app plays"
/// from this list; #96 plays them.
library;

enum Clip { move, capture, castle, check, end, music }

class ClipSpec {
  const ClipSpec(this.asset, {required this.loop});

  /// The asset path, as `pubspec.yaml` declares it.
  final String asset;

  /// A background bed that repeats seamlessly, rather than a one-shot.
  final bool loop;
}

const Map<Clip, ClipSpec> clips = {
  Clip.move: ClipSpec('assets/audio/move.wav', loop: false),
  Clip.capture: ClipSpec('assets/audio/capture.wav', loop: false),
  Clip.castle: ClipSpec('assets/audio/castle.wav', loop: false),
  Clip.check: ClipSpec('assets/audio/check.wav', loop: false),
  Clip.end: ClipSpec('assets/audio/end.wav', loop: false),
  Clip.music: ClipSpec('assets/audio/music.wav', loop: true),
};
