// Generates lib/engine/zobrist_keys.dart: the engine's Zobrist keys as
// committed constants, so the same position has the same key on every device
// and in every build (CLAUDE.md invariant 4). The keys come from SplitMix64
// with a fixed seed; test/engine/game_status_test.dart regenerates them and
// requires the committed file to match byte for byte.
//
// Usage: dart run tools/gen_zobrist.dart

import 'dart:io';

import 'package:honest_chess/engine/splitmix.dart';

/// The SplitMix64 seed. Changing it changes every key, and with them every
/// transposition-table entry and the computer's move choices.
const int seed = 0x486f6e6573744368; // "HonestCh" in ASCII

/// 12 pieces × 64 squares, one side-to-move key, four castling rights and
/// eight en-passant files.
const int keyCount = 12 * 64 + 1 + 4 + 8;

const String outputPath = 'lib/engine/zobrist_keys.dart';

/// The first [count] outputs of SplitMix64 from [seed].
List<int> splitMix64(int seed, int count) {
  final stream = SplitMix64(seed);
  return [for (var i = 0; i < count; i++) stream.next()];
}

/// [value] as an unsigned 64-bit hex literal, all sixteen digits.
String hex64(int value) {
  String half(int bits) => bits.toRadixString(16).padLeft(8, '0');
  return '0x${half((value >>> 32) & 0xffffffff)}${half(value & 0xffffffff)}';
}

/// The complete text of lib/engine/zobrist_keys.dart.
String zobristSource() {
  final out = StringBuffer()
    ..writeln('// GENERATED by tools/gen_zobrist.dart — do not edit by hand.')
    ..writeln('// SplitMix64, seed ${hex64(seed)}, $keyCount keys.')
    ..writeln()
    ..writeln('/// The Zobrist keys: `piece.index * 64 + square` for the 768')
    ..writeln('/// piece-square keys, then [zobristSide] (Black to move), the')
    ..writeln(
      '/// four castling rights from [zobristCastling] in `Castling` bit',
    )
    ..writeln(
      '/// order, and the eight en-passant files from [zobristEnPassant].',
    )
    ..writeln('const List<int> zobristKeys = [');
  for (final key in splitMix64(seed, keyCount)) {
    out.writeln('  ${hex64(key)},');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln('/// The index of the side-to-move key in [zobristKeys].')
    ..writeln('const int zobristSide = 768;')
    ..writeln()
    ..writeln('/// The index of the first castling key in [zobristKeys].')
    ..writeln('const int zobristCastling = 769;')
    ..writeln()
    ..writeln('/// The index of the a-file en-passant key in [zobristKeys].')
    ..writeln('const int zobristEnPassant = 773;');
  return out.toString();
}

void main() {
  File(outputPath).writeAsStringSync(zobristSource());
}
